; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
monitor_speed = 115200
;upload_speed = 460800
lib_deps =
  yoursunny/WifiEspNow @ ^0.0.20230713
  https://github.com/rtlopez/espnow-rclink/archive/refs/tags/v0.1.1.zip
;  EspNowRcLink=symlink://../espnow-rclink

build_flags =
  -std=gnu++17
  -Wall

build_unflags =
  -std=gnu++11
  -ggdb

[env:esp32]
platform = espressif32
board = lolin32
framework = arduino
extra_scripts = merge_firmware.py
lib_deps =
  ${env.lib_deps}
build_unflags =
  ${env.build_unflags}
build_flags =
  ${env.build_flags}
  -DPIN_PPM=13

[env:esp32c3_ppm]
board = esp32-c3-devkitm-1
platform = espressif32
framework = arduino
extra_scripts = merge_firmware.py
lib_deps =
  ${env.lib_deps}
build_unflags =
  ${env.build_unflags}
build_flags =
  ${env.build_flags}
  -DESP32C3
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DPIN_PPM=6

[env:esp32c3_analog]
board = esp32-c3-devkitm-1
platform = espressif32
framework = arduino
extra_scripts = merge_firmware.py
lib_deps =
  ${env.lib_deps}
build_unflags =
  ${env.build_unflags}
build_flags =
  ${env.build_flags}
  -DESP32C3
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DUSE_ANALOG=1
  -DPIN_POT0=0
  -DPIN_POT1=1
  -DPIN_POT2=3
  -DPIN_POT3=4
  -DPIN_SW0=8
  -DPIN_SW1=6
  -DPIN_SW2=-1
;  -DPRINT_INFO=1 ; print some details to console

[env:esp8266]
platform = espressif8266
board = d1_mini
framework = arduino
lib_deps =
  ${env.lib_deps}
build_unflags =
  ${env.build_unflags}
build_flags =
  ${env.build_flags}
  -DPIN_PPM=13
