; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[platformio]
extra_configs =
  platformio_local.ini

[local]
build_flags =

[env]
lib_deps =
  yoursunny/WifiEspNow @ ^0.0.20230713
  https://github.com/rtlopez/espnow-rclink/archive/refs/tags/v0.1.1.zip
;  EspNowRcLink=symlink://../espnow-rclink
  ESP32Async/AsyncTCP @ ^3.3.0
  ESP32Async/ESPAsyncWebServer @ ^3.6.0
build_flags =
  -std=gnu++17
  -Wall
  -D ASYNC_TCP_SSL_ENABLED=0
  ${local.build_flags}
build_unflags =
  -std=gnu++11
  -ggdb
board_build.embed_txtfiles =
  src/wireless/index.html
extra_scripts = 
  merge_firmware.py
monitor_speed = 115200
;upload_speed = 460800

[env:esp32]
platform = espressif32
board = lolin32
framework = arduino
lib_deps =
  ${env.lib_deps}
build_flags =
  ${env.build_flags}

[env:esp32s2]
board = esp32-s2-saola-1
platform = espressif32
framework = arduino
lib_deps =
  ${env.lib_deps}
  schnoog/Joystick_ESP32S2@^0.9.4
build_flags =
  ${env.build_flags}
  -D ESP32S2
  -D ARDUINO_USB_MODE=0
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D USE_GAMEPAD=1

[env:esp32s3]
board = lolin_s3_mini
platform = espressif32
framework = arduino
lib_deps =
  ${env.lib_deps}
  schnoog/Joystick_ESP32S2@^0.9.4
build_flags =
  ${env.build_flags}
  -D ESP32S3
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D USE_GAMEPAD=1

[env:esp32c3]
board = esp32-c3-devkitm-1
platform = espressif32
framework = arduino
lib_deps =
  ${env.lib_deps}
build_flags =
  ${env.build_flags}
  -D ESP32C3
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
